name: CI-CD-Pipeline-to-AWS-ElasticBreastalk
env:
  EB_PACKAGE_S3_BUCKET_NAME : "flask-app-packages1"
  EB_APLICATION_NAME        : "my_flask_app"
  EB_ENVIRONMENT_NAME       : "my_flask_app-env"
  DEPLOY_PACKAGE_NAME       : "flask_app_${{ github.sha }}.zip"
  AWS_REGION_NAME           : "eu-west-2"


on:
  push:
    branches:
      - master 
      
jobs:
  ci_part:
   runs-on: ubuntu-latest
   
   steps:
   - name: Git clone our repo
     uses: actions/checkout@v1
     
     
   - name: Create ZIP deployment package
     run : zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
  
